import pandas as pd
def column_mapping(df):
    column_mapping = {

    # Quantity sold
    "Quantity_Sold": "Quantity_Sold",
    "Quantity Sold": "Quantity_Sold",
    "quantity_sold": "Quantity_Sold",
    "quantity sold": "Quantity_Sold",
    "Quantity": "Quantity_Sold",
    "quantity": "Quantity_Sold",
    "Qty": "Quantity_Sold",
    "qty": "Quantity_Sold",
    "Qty Sold": "Quantity_Sold",
    "qty_sold": "Quantity_Sold",
    "qty sold": "Quantity_Sold",
    "Units Sold": "Quantity_Sold",
    "Units_Sold": "Quantity_Sold",
    "units_sold": "Quantity_Sold",
    "Units": "Quantity_Sold",
    "Number Sold": "Quantity_Sold",
    "Number_Sold": "Quantity_Sold",
    "Items Sold": "Quantity_Sold",
    "Items_Sold": "Quantity_Sold",

    # Unit price
    "Unit_Price": "Unit_Price",
    "Unit Price": "Unit_Price",
    "unit_price": "Unit_Price",
    "unit price": "Unit_Price",
    "Price": "Unit_Price",
    "price": "Unit_Price",
    "Item Price": "Unit_Price",
    "Item_Price": "Unit_Price",
    "Selling Price": "Unit_Price",
    "Selling_Price": "Unit_Price",
    "Sale Price": "Unit_Price",
    "Sale_Price": "Unit_Price",

    # Sales amount / revenue
    "Sales_Amount": "Sales_Amount",
    "Sales Amount": "Sales_Amount",
    "sales_amount": "Sales_Amount",
    "sales amount": "Sales_Amount",
    "Sales": "Sales_Amount",
    "sales": "Sales_Amount",
    "Revenue": "Sales_Amount",
    "revenue": "Sales_Amount",
    "Total Revenue": "Sales_Amount",
    "Total_Revenue": "Sales_Amount",
    "total_revenue": "Sales_Amount",
    "total revenue": "Sales_Amount",
    "Sales Revenue": "Sales_Amount",
    "Sales_Revenue": "Sales_Amount",
    "Total Sales": "Sales_Amount",
    "Total_Sales": "Sales_Amount",
    "Amount": "Sales_Amount",
    "Sales Value": "Sales_Amount",
    "Sales_Value": "Sales_Amount",

    # Product category
    "Product_Category": "Product_Category",
    "Product Category": "Product_Category",
    "product_category": "Product_Category",
    "product category": "Product_Category",
    "Category": "Product_Category",
    "category": "Product_Category",
    "Product Type": "Product_Category",
    "Product_Type": "Product_Category",
    "Type": "Product_Category",
    "Product Group": "Product_Category",
    "Product_Group": "Product_Category",
    "Department": "Product_Category",
    "Department Name": "Product_Category",
    "Department_Name": "Product_Category",

    # Region
    "Region": "Region",
    "region": "Region",
    "Area": "Region",
    "area": "Region",
    "Location": "Region",
    "location": "Region",
    "Country": "Region",
    "country": "Region",
    "State": "Region",
    "state": "Region",
    "Territory": "Region",
    "territory": "Region",
    "Market": "Region",
    "market": "Region",

    # Sale date
    "Sale_Date": "Sale_Date",
    "Sale Date": "Sale_Date",
    "sale_date": "Sale_Date",
    "sale date": "Sale_Date",
    "Date": "Sale_Date",
    "date": "Sale_Date",
    "Sales Date": "Sale_Date",
    "Sales_Date": "Sale_Date",
    "sales_date": "Sale_Date",
    "Transaction Date": "Sale_Date",
    "Transaction_Date": "Sale_Date",
    "transaction_date": "Sale_Date",
    "Order Date": "Sale_Date",
    "Order_Date": "Sale_Date",
    "Purchase Date": "Sale_Date",
    "Purchase_Date": "Sale_Date",}
    return df.rename(columns=column_mapping)